# Site Build Settings
title: "Yifan Yang"
description: "Assistant Professor of Linguistics at Shanghai Jiao Tong University, working on phonology, phonetics, morphology, reduplication, syllable structure, and understudied Chinese dialects."
author:
  name: "Yifan Yang"
  email: "yifanyang@sjtu.edu.cn"
url: "https://yifanyang08.github.io"
baseurl: ""
lang: "en"
locale: "en_US"
logo: "/assets/img/pic-01.jpg"
image: "/assets/img/pic-01.jpg"

markdown: kramdown
highlighter: rouge
permalink: pretty
plugins:
  - jekyll-sitemap
  - jekyll-seo-tag

social:
  name: "Yifan Yang"
  links:
    - "https://orcid.org/0000-0003-0479-9713"
    - "https://scholar.google.com/citations?user=sCwe79gAAAAJ&hl=en"
    - "https://www.linkedin.com/in/yifanyang08/"
    - "https://github.com/yifanyang08"
