google-ID: ''

show_language_switcher: false

social:
- {icon: 'orcid', label: 'ORCID', link: 'https://orcid.org/0000-0003-0479-9713'}
- {icon: 'google-scholar', label: 'Google Scholar', link: 'https://scholar.google.com/citations?user=sCwe79gAAAAJ&hl=en'}
- {icon: 'linkedin', label: 'LinkedIn', link: 'https://www.linkedin.com/in/yifanyang08/'}
- {icon: 'github', label: 'GitHub', link: 'https://github.com/yifanyang08'}
- {icon: 'email', label: 'Email', link: 'mailto:yifanyang@sjtu.edu.cn'}
